In [2]:
import scipy.sparse as sp
import scipy.sparse.linalg

In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
A = np.array([[1,2,0,0],[0,3,4,0],[0,0,5,6],[7,0,8,9]])
A

array([[1, 2, 0, 0],
       [0, 3, 4, 0],
       [0, 0, 5, 6],
       [7, 0, 8, 9]])

In [9]:
A = sp.csr_matrix(A)

In [10]:
A.data
# 0이 아닌 모든 요소들을 행을 순서로 묶은것

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [11]:
A.indices
# 각 행에서 0이 아닌 모든 요소들의 index를 묶은것

array([0, 1, 1, 2, 2, 3, 0, 2, 3], dtype=int32)

In [12]:
A.indptr
# indices에서 각 행이 시작되는 index를 묶은것

array([0, 2, 4, 6, 9], dtype=int32)

In [13]:
i = 2
# 2행

In [14]:
A.indptr[i], A.indptr[i+1]-1
# 2행에서 0이 아닌 값이 위치한 indices의 index

(4, 5)

In [17]:
A.data[4], A.data[5]
# 2행의 0이아닌 요소의 값

(5, 6)

In [15]:
A.indices[A.indptr[i]:A.indptr[i+1]]
# 2행의 2번째 3번째 index에 0이 아닌 요소가 존재

array([2, 3], dtype=int32)

In [18]:
i = 3
# 3행

In [19]:
A.indptr[i], A.indptr[i+1]-1
# 3행에서 0이 아닌 값이 위치한 indices의 index

(6, 8)

In [24]:
A.data[6], A.data[7], A.data[8]
# 3행에서 0이아닌 요소의 값

(7, 8, 9)

In [25]:
A.indices[A.indptr[i]:A.indptr[i+1]]
# 3행에서 0이 아닌 요소의 index

array([0, 2, 3], dtype=int32)