In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr1.shape

(2, 3)

In [4]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [5]:
arr2.shape

(2, 3)

In [6]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [7]:
arr1*arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [8]:
arr1/arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1.shape

(2, 3)

In [11]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [12]:
arr3.shape

(3,)

In [13]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [14]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)