In [1]:
import numpy as np

In [2]:
names = np.array(['Beomwoo','Bemwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Bemwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [3]:
names.shape

(8,)

In [6]:
data = np.random.randn(8,4)
data
#np.random.randn() 함수는 기대값이 0이고 표준편차가 1인 가우시안 정규분표를 따르는 난수를 발생시킨다. 받은 크기만큼  array를 만든다.

array([[-1.33983709,  0.38753615, -1.59149929, -1.14769466],
       [-1.09105066,  0.77293973,  1.0587485 ,  0.58829177],
       [-0.09108669,  0.07230086, -1.76196973,  0.36664878],
       [ 1.12467909, -0.23258515, -0.39158065,  0.7567663 ],
       [-0.31845384, -1.08102706,  0.69182289,  0.915221  ],
       [ 0.45463799, -0.77485903,  1.64278572,  2.2332238 ],
       [ 2.22095845, -0.14892573, -0.89451892, -1.22970396],
       [-0.63199734, -0.69587933,  2.6647023 , -1.33270408]])

In [7]:
data.shape

(8, 4)

위와 같은 names와 data라는 array가 있다.
이때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자
그리고 이 때, names가 Beomwoo인 행의 data만 보고 싶을 때
다음과 같이 마스크를 사용한다.

In [8]:
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True, False, False, False, False,  True, False,  True])

In [9]:
data[names_Beomwoo_mask,:]

array([[-1.33983709,  0.38753615, -1.59149929, -1.14769466],
       [ 0.45463799, -0.77485903,  1.64278572,  2.2332238 ],
       [-0.63199734, -0.69587933,  2.6647023 , -1.33270408]])

위의 결과를 보면, 요소가 Beomwoo인 것은 0번째, 1번째, 5번째, 7번째 이므로 data에서 0,1,5,7행의 모든 요소를 꺼내와야 한다
이를 위해 요소가 Beomwoo인 것에 대한 boolean값을 가지는 mask를 만들었고 마스크를 인덱싱에 응용하여 data의 0,1,5,7행을 꺼냈다.

In [10]:
data[names == 'Kim',:]
#요소가 Kim인 행의 데이터만 꺼내기

array([[-0.09108669,  0.07230086, -1.76196973,  0.36664878]])

In [12]:
data[(names == 'Kim')|(names == 'Park'),:]
#논리연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기

array([[-0.09108669,  0.07230086, -1.76196973,  0.36664878],
       [ 2.22095845, -0.14892573, -0.89451892, -1.22970396]])

data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.
data array에서 0번째 열의 값이 0보다 작은 행을 구해보자.

In [13]:
data[:,0] < 0
#먼저 마스크를 만든다
#data array에서 0번째 열이 0보다 작은 요소의 boolean값은 다음과 같다

array([ True,  True,  True, False,  True, False, False,  True])

In [14]:
data[data[:,0]<0,:]
#위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.

array([[-1.33983709,  0.38753615, -1.59149929, -1.14769466],
       [-1.09105066,  0.77293973,  1.0587485 ,  0.58829177],
       [-0.09108669,  0.07230086, -1.76196973,  0.36664878],
       [-0.31845384, -1.08102706,  0.69182289,  0.915221  ],
       [-0.63199734, -0.69587933,  2.6647023 , -1.33270408]])

이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.
위에서 얻은, 0번째 열의 값이 0보다 작은 행의 2,3번째 열값에 0을 대입해보자.

In [15]:
data[data[:,0]<0,2:4]
#0번째 열의 값이 0보다 작은 행의 2,3번째 열 값

array([[-1.59149929, -1.14769466],
       [ 1.0587485 ,  0.58829177],
       [-1.76196973,  0.36664878],
       [ 0.69182289,  0.915221  ],
       [ 2.6647023 , -1.33270408]])