In [1]:
import numpy as np

In [4]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1[0]
# 0번째 요소

0

In [6]:
arr1[3]
# 3번째 요소

3

In [7]:
arr1[3:9]
# 3번째 부터 8번째

array([3, 4, 5, 6, 7, 8])

In [8]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr2[0,0]
# 2차원 array에서 인덱싱 하기 위해선 2개의 좌표를 입력해야한다.

1

In [12]:
arr2[2,:]
# 2행의 모든 요소 꺼내기

array([ 9, 10, 11, 12])

In [13]:
arr2[2,3]

12

In [ ]:
arr2[:,3]
#모든 행의 3번째 요소 꺼내기