In [1]:
import numpy as np

In [2]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [7]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [5]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr1.shape
#array의 형태를 확인

(5,)

In [9]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [18]:
arr2.shape

(5,)

숫자가 하나 : 1차원 data
5: 크기

In [11]:
arr2.dtype
#array의 자료형을 확인

dtype('int32')

In [13]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [14]:
arr3.shape

(5,)

In [15]:
arr3.dtype

dtype('float64')

In [16]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr4.shape

(4, 3)

숫자가 둘 : 2차원 data
4 * 3: 크기