In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
#인자로 받는 크기만큼, 모든 요소가 1인 array를 만듬

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
#인자로 받는 값에 1씩 증가하는 1차원 array를 만듬