하나의 array에 적용되는 함수

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randn(5,3)
arr1

array([[-0.23140394,  0.33555542,  0.52347635],
       [-0.01747135,  0.10191311, -1.40627927],
       [-0.1569677 , -0.37141807, -0.78823118],
       [ 0.75971329,  0.1045167 ,  1.40339088],
       [-1.17493323, -0.04352878,  0.71667052]])

In [3]:
np.abs(arr1)
#각 성분의 절대값

array([[0.23140394, 0.33555542, 0.52347635],
       [0.01747135, 0.10191311, 1.40627927],
       [0.1569677 , 0.37141807, 0.78823118],
       [0.75971329, 0.1045167 , 1.40339088],
       [1.17493323, 0.04352878, 0.71667052]])

In [6]:
np.sqrt(np.abs(arr1))
#각 성분의 제곱근

array([[0.48104463, 0.57927146, 0.72351665],
       [0.13217924, 0.31923833, 1.18586646],
       [0.3961915 , 0.60944078, 0.88782384],
       [0.87161533, 0.32329043, 1.184648  ],
       [1.08394337, 0.20863552, 0.84656395]])

In [7]:
np.square(arr1)
#각 성분의 제곱 계산

array([[5.35477811e-02, 1.12597441e-01, 2.74027486e-01],
       [3.05248151e-04, 1.03862818e-02, 1.97762137e+00],
       [2.46388598e-02, 1.37951381e-01, 6.21308392e-01],
       [5.77164280e-01, 1.09237414e-02, 1.96950596e+00],
       [1.38046810e+00, 1.89475473e-03, 5.13616640e-01]])

In [8]:
np.exp(arr1)
#각 성분을 e의 지수로 삼은 값 계산

array([[0.79341891, 1.39871705, 1.68788514],
       [0.98268039, 1.10728725, 0.24505337],
       [0.85473166, 0.68975552, 0.45464828],
       [2.13766324, 1.11017394, 4.06897399],
       [0.3088396 , 0.957405  , 2.0476044 ]])

In [10]:
np.log(arr1)
np.log10(arr1)
np.log2(arr1)
#각 성분을 로그를 씌운 값을 계산하기

C:\Users\shpar\AppData\Local\Temp/ipykernel_32688/159011308.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr1)
C:\Users\shpar\AppData\Local\Temp/ipykernel_32688/159011308.py:2: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1)
C:\Users\shpar\AppData\Local\Temp/ipykernel_32688/159011308.py:3: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1)


array([[        nan, -1.57537703, -0.93380374],
       [        nan, -3.29458846,         nan],
       [        nan,         nan,         nan],
       [-0.39647304, -3.25819456,  0.48891689],
       [        nan,         nan, -0.48061808]])

In [11]:
np.sign(arr1)
#각 성분의 부호 계산

array([[-1.,  1.,  1.],
       [-1.,  1., -1.],
       [-1., -1., -1.],
       [ 1.,  1.,  1.],
       [-1., -1.,  1.]])

In [12]:
np.ceil(arr1)
#각 성분의 소수 첫번째 자리 올림 값

array([[-0.,  1.,  1.],
       [-0.,  1., -1.],
       [-0., -0., -0.],
       [ 1.,  1.,  2.],
       [-1., -0.,  1.]])

In [13]:
np.floor(arr1)
#각 성분의 소수 첫번째 자리 내림 값

array([[-1.,  0.,  0.],
       [-1.,  0., -2.],
       [-1., -1., -1.],
       [ 0.,  0.,  1.],
       [-2., -1.,  0.]])

In [14]:
np.isnan(arr1)
#각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
np.isnan(np.log(arr1))

C:\Users\shpar\AppData\Local\Temp/ipykernel_32688/3789410203.py:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(arr1))


array([[ True, False, False],
       [ True, False,  True],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [17]:
np.isinf(arr1)
#각 성분이 무한대인 경우 True를, 아닌 경우 Flase를 반환

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [20]:
np.cos(arr1)
#각 성분에 삼각함수 값 계산

array([[0.97334537, 0.94422756, 0.86608661],
       [0.99984738, 0.99481135, 0.16377593],
       [0.98770584, 0.93181361, 0.7051007 ],
       [0.7250335 , 0.9945431 , 0.16662463],
       [0.38560468, 0.99905277, 0.75399696]])

In [21]:
np.tanh(arr1)

array([[-0.22736014,  0.3235037 ,  0.48037861],
       [-0.01746957,  0.10156174, -0.88670141],
       [-0.15569111, -0.35523146, -0.65740584],
       [ 0.64090805,  0.10413779,  0.8860824 ],
       [-0.82584723, -0.04350131,  0.61484271]])

두 개의 array에 적용되는 함수

In [22]:
arr1

array([[-0.23140394,  0.33555542,  0.52347635],
       [-0.01747135,  0.10191311, -1.40627927],
       [-0.1569677 , -0.37141807, -0.78823118],
       [ 0.75971329,  0.1045167 ,  1.40339088],
       [-1.17493323, -0.04352878,  0.71667052]])

In [23]:
arr2 = np.random.randn(5,3)
arr2

array([[ 0.17581431, -0.9942876 , -0.68279707],
       [ 1.92432604, -0.71541626, -2.2039767 ],
       [ 0.92335123, -1.07413472, -1.80763574],
       [ 0.94213836,  1.16853817,  1.93816956],
       [ 1.08340896, -0.96227318,  0.4740245 ]])

In [27]:
np.add(arr1,arr2)
np.subtract(arr1,arr2)
np.multiply(arr1,arr2)
np.divide(arr1,arr2)


#두 개의 array에 대해 동일한 위치의 성분끼리 연산하기

array([[-1.31618376, -0.33748326, -0.76666461],
       [-0.00907921, -0.14245288,  0.63806449],
       [-0.16999783,  0.3457835 ,  0.43605642],
       [ 0.80637125,  0.08944227,  0.72408055],
       [-1.08447804,  0.04523537,  1.51188498]])

In [28]:
np.maximum(arr1,arr2)
np.minimum(arr1,arr2)
#두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기

array([[-0.23140394, -0.9942876 , -0.68279707],
       [-0.01747135, -0.71541626, -2.2039767 ],
       [-0.1569677 , -1.07413472, -1.80763574],
       [ 0.75971329,  0.1045167 ,  1.40339088],
       [-1.17493323, -0.96227318,  0.4740245 ]])

통계 함수

In [29]:
arr1

array([[-0.23140394,  0.33555542,  0.52347635],
       [-0.01747135,  0.10191311, -1.40627927],
       [-0.1569677 , -0.37141807, -0.78823118],
       [ 0.75971329,  0.1045167 ,  1.40339088],
       [-1.17493323, -0.04352878,  0.71667052]])

In [30]:
np.sum(arr1)
#전체 성분의 합을 계산

-0.24499724120578215

In [31]:
np.sum(arr1,axis=1)
#열 간의 합을 계산

array([ 0.62762783, -1.32183751, -1.31661695,  2.26762087, -0.50179149])

In [32]:
np.sum(arr1,axis=0)
#행 간의 합을 계산

array([-0.82106293,  0.12703839,  0.44902731])

In [33]:
np.mean(arr1)
#전체 성분의 평균을 계산

-0.01633314941371881

In [34]:
np.mean(arr1, axis=0)
#행 간의 평균을 계산

array([-0.16421259,  0.02540768,  0.08980546])

In [35]:
np.std(arr1)
np.var(arr1)
np.min(arr1)
np.max(arr1)
#전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)

1.403390877941109

In [37]:
np.min(arr1,axis=1)

array([-0.23140394, -1.40627927, -0.78823118,  0.1045167 , -1.17493323])

In [43]:
np.argmax(arr1)
np.argmin(arr1)
#전체 성분의 최소, 최대값이 위치한 인덱스를 반환

5

In [40]:
np.argmax(arr1,axis=0)
#행간 최대값이 위치한 인덱스 반환

array([3, 0, 3], dtype=int64)

In [44]:
np.cumsum(arr1)
np.cumprod(arr1)
#맨 처음 성분부터 각 성분까지의 누적합 또는 누적곲을 계산

array([-2.31403935e-01, -7.76488450e-02, -4.06473338e-02,  7.10163888e-04,
        7.23750097e-05, -1.01779476e-04,  1.59760905e-05, -5.93380867e-06,
        4.67721300e-06,  3.55334087e-06,  3.71383475e-07,  5.21196181e-07,
       -6.12370712e-07,  2.66557503e-08,  1.91033905e-08])

In [45]:
np.cumsum(arr1,axis=1)

array([[-0.23140394,  0.10415149,  0.62762783],
       [-0.01747135,  0.08444176, -1.32183751],
       [-0.1569677 , -0.52838577, -1.31661695],
       [ 0.75971329,  0.86422999,  2.26762087],
       [-1.17493323, -1.21846201, -0.50179149]])

기타 함수

In [46]:
arr1

array([[-0.23140394,  0.33555542,  0.52347635],
       [-0.01747135,  0.10191311, -1.40627927],
       [-0.1569677 , -0.37141807, -0.78823118],
       [ 0.75971329,  0.1045167 ,  1.40339088],
       [-1.17493323, -0.04352878,  0.71667052]])

In [47]:
np.sort(arr1)
#전체 성분에 대해서 오름차순으로 정렬

array([[-0.23140394,  0.33555542,  0.52347635],
       [-1.40627927, -0.01747135,  0.10191311],
       [-0.78823118, -0.37141807, -0.1569677 ],
       [ 0.1045167 ,  0.75971329,  1.40339088],
       [-1.17493323, -0.04352878,  0.71667052]])

In [50]:
np.sort(arr1)[::-1]
#전체 성분에 대해서 내림차 순으로 정렬

array([[-1.17493323, -0.04352878,  0.71667052],
       [ 0.1045167 ,  0.75971329,  1.40339088],
       [-0.78823118, -0.37141807, -0.1569677 ],
       [-1.40627927, -0.01747135,  0.10191311],
       [-0.23140394,  0.33555542,  0.52347635]])

In [51]:
np.sort(arr1,axis=0)
#행 방향으로 오름차순으로 정렬

array([[-1.17493323, -0.37141807, -1.40627927],
       [-0.23140394, -0.04352878, -0.78823118],
       [-0.1569677 ,  0.10191311,  0.52347635],
       [-0.01747135,  0.1045167 ,  0.71667052],
       [ 0.75971329,  0.33555542,  1.40339088]])